spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
  graphql:
    path: /graphql
    schema:
      file-extensions:
        - .graphqls
        - .graphql
    graphiql:
      enabled: true
    websocket:
      path: /graphql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://securetoken.google.com/choices-41be5"
  main:
    allow-bean-definition-overriding: true